dotenv: .env
dependencies:
# take data from GitHub > format: <organization>/<repo>@<version>
- smartcontractkit/chainlink-brownie-contracts@0.3.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.1'
networks:
  mainnet:
    eth_usd_priceFeed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: True
  mainnet-fork-dev:
    eth_usd_priceFeed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  rinkeby:
    eth_usd_priceFeed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  kovan:
    eth_usd_priceFeed: '0x9326BFA02ADD2366b30bacB125260Af641031331'
    verify: True
  development:
    verify: False
  ganache-desktop:
    verify: False
